export const SIGNED_IN = "SIGNED_IN"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const REGISTER = "REGISTER"
export const UPDATE_IMAGE = "UPDATE_IMAGE"
export const GET_ALL_USERS = "GET_ALL_USERS"


export const CREATE_CLASS = "CREATE_CLASS"
export const GET_CLASS = "GET_CLASS"
export const ENROLL_CLASS = "ENROLL_CLASS"
export const GET_ALL_CLASSES = "GET_ALL_CLASSES"
export const GET_MY_CLASSES = "GET_MY_CLASSES"

export const GET_ALL_ABSCENCES = "GET_ALL_ABSCENCES"
export const SET_ABSCENCE = "SET_ABSCENCE"
export const CHANGE_ABSCENCE_STATUS = "CHANGE_ABSCENCE"

export const GET_ALL_SUBJECTS = "GET_ALL_SUBJECTS"
export const GET_SUBJECT_CLASSES = "GET_SUBJECT_CLASSES"
export const GET_ENROLLED_SUBJECTS = "GET_ENROLLED_SUBJECTS"
export const ENROLL_SUBJECT = "ENROLL_SUBJECT"
export const CREATE_SUBJECT = "CREATE_SUBJECT"
